services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

# Part 1
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: testdb
    ports:
      - "3000:3000"

  # app:
  #   image: joshphampolymtl/docker-demo:latest   # <-- pulled from Docker Hub
  #   depends_on:
  #     - db
  #   environment:
  #     DB_HOST: db
  #     DB_USER: root
  #     DB_PASSWORD: rootpass
  #     DB_NAME: testdb
  #   ports:
  #     - "3000:3000"


